services:
  aws-resources-wait:
    container_name: s-aws-resources-wait
    image: amazonlinux:2
    entrypoint:
      - /bin/sh
      - -c
      - |
        yum -y install awscli &&
        export AWS_DEFAULT_REGION=${AWS_REGION} &&
        /usr/local/bin/wait-for.sh &&
        tail -f /dev/null
    volumes:
      - ./aws-resources/wait-for.sh:/usr/local/bin/wait-for.sh:ro
    extra_hosts:
      - localhost.localstack.cloud:host-gateway
      - host.docker.internal:host-gateway
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    healthcheck:
      test: ["CMD", "aws", "kinesis", "list-streams"]
      interval: 30s
      timeout: 10s
      retries: 3
