services:
  stream-collector:
    container_name: s-stream-collector
    image: snowplow/scala-stream-collector-kinesis:3.2.0-distroless
    command: ["--config", "/snowplow/collector/config.hocon"]
    restart: always
    ports:
      - 9090:8080
    environment:
      - ACCEPT_LICENSE=${ACCEPT_LICENSE}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SNOWBRIDGE_CONFIG_FILE=/config/snowbridge-config.hcl
    volumes:
      - ./stream-collector/config.hocon:/snowplow/collector/config.hocon
    extra_hosts:
      - localhost.localstack.cloud:host-gateway
      - host.docker.internal:host-gateway

  enrich:
    container_name: s-enrich
    image: snowplow/snowplow-enrich-kinesis:5.0.0-distroless
    command: ["--config", "/snowplow/enrich/enrich.hocon", "--iglu-config", "/snowplow/iglu-client/iglu_resolver.json", "--enrichments", "/snowplow/enrich/enrichments"]
    restart: always
    environment:
      - ACCEPT_LICENSE=${ACCEPT_LICENSE}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL:-}
    volumes:
      - ./enrich:/snowplow/enrich
      - ./iglu-client:/snowplow/iglu-client
    extra_hosts:
      - localhost.localstack.cloud:host-gateway
      - host.docker.internal:host-gateway
    depends_on:
      stream-collector:
        condition: service_started

  snowbridge:
    container_name: s-snowbridge
    image: snowplow/snowbridge:2.4.2-aws-only
    command: ["/opt/snowplow/snowbridge"]
    environment:
      - ACCEPT_LICENSE=${ACCEPT_LICENSE}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL:-}
      - JS_SCRIPT_PATH=/snowbridge/video-data.js
      - SNOWBRIDGE_CONFIG_FILE=/snowbridge/config.hcl
    volumes:
      - ./snowbridge:/snowbridge
    extra_hosts:
      - localhost.localstack.cloud:host-gateway
      - host.docker.internal:host-gateway
    depends_on:
      enrich:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully
    restart: unless-stopped
