services:
  localstack:
    container_name: s-localstack
    image: localstack/localstack:4.2.0
    restart: always
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      - AWS_DEFAULT_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - SERVICES=sts,dynamodb,kinesis,cloudwatch
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1
      - KINESIS_LATENCY=0
    volumes:
      - ${TMPDIR:-/tmp}/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ../localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
