= labs/{project-dir}
include::common/head.adoc[]

:uri-state-machine: link:../../../live-viewer-backend/src/main/java/com/snowplowanalytics/liveviewerprofile/service/VideoStateMachine.java

This lab runs Snowbridge using Docker and a transformation made by the script `script.<number>.js`.
So, you can specify the script to execute by running a shell script (link:run.sh[]).

The output generated by Snowbridge is copied to `output.<number>.txt`.

Execute the link:run.sh[] script and you will get more details.

== Issue

Take a look at the order of events generated by Snowplow Micro when it was collected in the file `data.tsv`:

[,console]
----
$ ./events-from-snowplow.sh > events-from-snowplow.sh.txt
----
.Output
[%collapsible]
[,txt]
====
[.scrollable-block]
.events-from-snowplow.sh.txt:
----
include::events-from-snowplow.sh.txt[]
----
====

You can observe that the order `collector_tstamp` (first field) is increasing as expected.

.Click here to see some details about this script
[%collapsible]
====
Here is the source code:

[,bash]
.link:events-from-snowplow.sh[]:
----
include::events-from-snowplow.sh[]
----

This scripts uses the file `data.tsv.txt` witch is generated from `data.tsv` by using the script link:data/tsv-debug.sh[].
====

But, the order for `collecor_tstamp` was not replicated correctly in the output generated by Snowbridge:

[,console]
----
$ ./events-from-snowbridge.sh > events-from-snowbridge.sh.txt
----
.Output

[%collapsible]
====
[.scrollable-block]
.events-from-snowbridge.sh.txt:
----
include::events-from-snowbridge.sh.txt[]
----
====

WARNING: This is a serious issue because {uri-state-machine}[a state machine that determines the video] status won’t work correctly without events occurring in order.

.Click here to see some details about this script
[%collapsible]
====
Here is the code of the script above:

[,bash]
.link:events-from-snowbridge.sh[]:
----
include::events-from-snowbridge.sh[]
----

It basically generates the output above from the file `output.6.txt`. This is the first two lines from this file:

----
include::output.6.txt[lines=1..2]
----

This file contains only the `Data` part from the full output generated by Snowbridge:

[,bash]
----
include::run.sh[tag=data]
----

Snowbridge is called by `run.sh` this way:

[,bash]
----
include::run.sh[tag=docker]
----

Here is the content from file link:config.hcl[]:

[,hcl]
----
include::config.hcl[]
----

And here is the link:script.6.js[] file's content:

[,javascript]
----
include::script.6.js[]
----

Here is the command to generate the file `output.6.txt`:

[,console]
----
$ ./run.sh 6
----
====
